# Generated by Django 5.1.2 on 2024-11-06 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_goods_parcels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parcels',
            new_name='Delivery',
        ),
        migrations.AlterModelTable(
            name='delivery',
            table='delivery',
        ),
        migrations.AlterModelTable(
            name='goods',
            table='goods',
        ),
    ]
