# Generated by Django 5.1.2 on 2024-11-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_parcels_delivery_alter_delivery_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='id',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='id',
        ),
        migrations.AddField(
            model_name='delivery',
            name='parcel_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
