# Generated by Django 5.1.2 on 2024-11-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_delivery_id_remove_goods_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='goods_id',
            new_name='product_id',
        ),
    ]
